export { createEditor } from './create-editor.js'
export type { CreateEditorOptions } from './create-editor.js'
export { livePreview } from './live-preview/index.js'
export { wikilinkDecoration, setWikiLinkClickHandler } from './wikilink-decoration.js'
export { wikilinkCompletion } from './autocomplete/wikilink-completion.js'
export type { WikiLinkCompletionSource } from './autocomplete/wikilink-completion.js'
export { vaultEditorTheme } from './theme.js'
export { tableEditor, createBlankTable } from './table/index.js'
export { collapsibleHeadings } from './live-preview/collapse.js'
export { frontmatterEditor } from './frontmatter/index.js'
